### ISSUE TITLE
On the STL10 dataset during linear evaluation

### ISSUE THREAD

**Issue by songweige** [joshr17/HCL#4]
Hi, it looks like the STL10 training set used for linear evaluation should split 'train' instead of 'train+unlabel'. Could you please confirm this is the right way to go? thx

**Comment by joshr17** [comment]
Yes that's the right configuration - since for linear training we require all samples to have labels, so we cannot use the unlabeled data.

Thanks for the question!

**Comment by songweige** [comment]
Thanks for confirming!
