### ISSUE TITLE
Beta in reweight

### ISSUE THREAD

**Issue by HannesStark** [joshr17/HCL#5]
Thank you for the awesome repository!

Here we use the beta concentration in the exponent:
https://github.com/joshr17/HCL/blob/36e39344f8a11fe4849c2c4c10451b2f4d8fa939/image/main.py#L43-L44

Is that not different from what is described in the [paper](https://openreview.net/forum?id=CR1XOQ0UTh-) where we do not have the beta in the exponent in the pseudocode in Figure 13:

`reweight = (beta*neg) / neg.mean()`

What am I missing?

**Comment by joshr17** [comment]
Hi Hannes - thanks for the question! The pseudocode has a typo - the code in the repo is correct and is the same as the method as described mathematically in Sec 3.1 of the paper.
