### ISSUE TITLE
[documentation] Pair descriptions

### ISSUE THREAD

**Issue by Steven-N-Hart** [joshr17/HCL#6]
When processing images using the [utils script](https://github.com/joshr17/HCL/blob/main/image/utils.py) , could you clarify the definitions of the inputs? 

I'm assuming:
* `self.targets`:  a list of reference image
* `self.data`:   a list of images of an alternate class

In this way I would expect that the `__get_item__()` would return either
 1. two random transformations of the images from a different class, plus the original target
 2.  Or if using the positive pair strategy, return 1 augmented non class image, 1 augmented image of the same class, and the target.
 
Could you confirm if I have this correct?

**Comment by joshr17** [comment]
Hi Steven,

`self.targets` and `self.data` are lists that store the full dataset and each samples label (if there are no labels, then `self.targets` is a list of `None`'s. I suspect the reason this is a little confusing here is that these variables are not explicitly defined in my code. Instead, for the three datasets I look at here (CIFAR10, CIFAR100, STL10) all of these attributes are inherited from their base class from the torch library (see e.g. the definition of `CIFAR10Pair`). 

To see a concrete example of what these look like then I recommend loading the torch CIFAR10 dataset and simply printing these two variables. 

Hope this helps,

Josh

**Comment by joshr17** [comment]
Feel free to re-open if you have any further questions!
